version: 2
jobs:
  build:
    working_directory: ~/vue-auto-form-field
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint -- --no-fix
      - run: yarn test:unit
      - run: yarn build

  publish:
    working_directory: ~/vue-auto-form-field
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run:
          name: yarn-version
          command: |
            MESSAGE=`git log -1 --pretty=%B`
            MESSAGE=`echo $MESSAGE | grep -oP "tag=\K[^ ]+"`
            if [ -z "$MESSAGE" ]; then
              echo "Please specify a tag for your release"
              exit 1
            else
              yarn publish --tag=$MESSAGE
            fi

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
